### ISSUE TITLE
Time Crate for token signer is not very up to date

### ISSUE THREAD

**Issue by IsaacJReay** [michaelvanstraten/actix-jwt-auth-middleware#11]
Hello there!

I am receiving error about crate `time` versioning conflict error when I use other crate (eg: Actix-web) which uses later version of the aforementioned crate (v0.2+). However, your crate still use version up to 0.1.45, which, in all newer version (0.2+ --> 0.3.33), have put the module `time::duration::Duration` into private, and use directly `time::Duration`. The reasons i brought this up is because whenever I compile my project, it conflict the versions used later and yours by your crate. It would be very much helpful if you could kindly update the `time` crate dependencies of your crate to version 2 or newer, or so I thought how it should work.

Below I have attached an image of the conflict error. Please let me know if you need something else from me.

![Screenshot_20230726_163929](https://github.com/michaelvanstraten/actix-jwt-auth-middleware/assets/57164703/c71930b1-afc1-47be-a0aa-063309a113ba)

**Comment by michaelvanstraten** [comment]
Hi Isaac,

sorry for the wait, I am currently on holiday.

The error you are getting is not related to versioning issues, but to the fact that the Duration struct you are passing is not the correct type. The type you passed originates from the time crate, the type that is required is the Duration type from the chrono crate. 

I took a look at the documentation and noticed that the referenced type is the time::Duration type not the chrono::Duration type, this is very odd. 

Could you send me the current git commit you are on?

**Comment by IsaacJReay** [comment]
I used the latest v0.3.0 straight from https://crates.io. I literally do not know what commit it came from, though. But, i saw that you already made some changes to main a short while ago

**Comment by michaelvanstraten** [comment]
I response to your issue I made the public interface use the `std::time::Duration` instead. Does that fix your issue?

But I think I will be retracting this commit because the std Duration does not offer convenient options to initialize longer durations.

**Comment by IsaacJReay** [comment]
Yes, it works when you use the `std::time::Duration`. And like you have said, It is very difficult to set longer duration. And, i found that when I tried to build release with the git version, `derive-elves` caused error that said it cannot be used for stable release channel. But anyway, I would love to go back to `Chrono` crate, but could you make it work properly, or is there other solution you may try?

**Comment by michaelvanstraten** [comment]
I will get to it as soon as I can.
