### ISSUE TITLE
enable_authorization_header not available in version 0.3.0 of published crate

### ISSUE THREAD

**Issue by 0xAnansi** [michaelvanstraten/actix-jwt-auth-middleware#13]
It is not possible to allow extraction of the claims from the Authorization header using the "enable _authorization_header" function in the version 0.3.0 of the crate (latest available atm).

Looking at the sources, seems that it disappeared:

authority.rs
```rust

 #[builder(setter(into))]
    pub(crate) refresh_token_name: String,
    /**
        If set to true the clients refresh token will automatically refreshed,
        this allows clients to basically stay authenticated over a infinite amount of time, so i don't recommend it.

        Defaults to `false`
    */
    #[builder(default = "false")]
    renew_refresh_token_automatically: bool,
    /**
       If set to true, the service will look for `access_token_name` and `refresh_token_name` in
       http headers.
    */
    #[builder(default = "false")]
    enable_header_tokens: bool,
    /**
       If set to true, the service will look for `access_token_name` and `refresh_token_name` in
       in the query parameters.
    */
    #[builder(default = "false")]
    enable_query_tokens: bool,
    /**
       If set to true, the service will look for `access_token_name` and `refresh_token_name` in
       in the cookies of the processed request.
    */
    #[builder(default = "true")]
    enable_cookie_tokens: bool,
    /**
        Key used to verify integrity of access and refresh token.
    */
    verifying_key: Algo::VerifyingKey,
    /**
        The Cryptographic signing algorithm used in the process of creation of access and refresh tokens.

        Please referee to the [`Supported algorithms`](https://docs.rs/jwt-compact/latest/jwt_compact/#supported-algorithms) section of the `jwt-compact` crate for a comprehensive list of the supported algorithms.

        Defaults to the value of the `algorithm` field set on the `token_signer`, if the `token_signer` is not set,
        this field needs to be set.
    */
    #[builder(default = "pull_from_token_signer!(self, algorithm)")]
    algorithm: Algo,
    /**
        Used in the creating of the `token`, the current time stamp is taken from this, but please referee to the Structs documentation.

        Defaults to the value of the `time_options` field set on the `token_signer`, if the `token_signer` is not set,
        this field needs to be set.
    */
    #[builder(default = "pull_from_token_signer!(self, time_options)")]
    time_options: TimeOptions,
    /**
       Not Passing a [`TokenSigner`] struct will make your middleware unable to refresh the access token automatically.

       You will have to provide a algorithm manually in this case because the Authority can not pull it from the `token_signer` field.

       Please referee to the structs own documentation for more details.
    */
    #[builder(default = "None")]
    token_signer: Option<TokenSigner<Claims, Algo>>,
    #[doc(hidden)]
    #[builder(setter(skip), default = "PhantomData")]
    claims_marker: PhantomData<Claims>,
    #[doc(hidden)]
    #[builder(setter(skip), default = "PhantomData")]
    args_marker: PhantomData<Args>,
}

```

I can see it in the current version published on github, so I'm not sure what went wrong during the crate publication.

**Comment by michaelvanstraten** [comment]
I'm sorry for the late response.
According to the file tree, at the state of the current commit d24f3f41fdeaeccc84595750246c0df778c2e6e1, there exists a `enable_authorization_header` field on the `Authority` struct. 

Could you share the commit where you can find this deficit? 

It could be that the version with this flag has not yet been released to `crates.io`. In this case you can just replace the `version` in your `Cargo.toml` with a `git` and `ref` to the latest commit in this repository.

**Comment by michaelvanstraten** [comment]
Im typing this from my phone since it is already pretty late in Germany so sorry if the above is incorrect, I only have info the GitHub mobile app provides.

I will look into this further when I get up.

**Comment by 0xAnansi** [comment]
No problem, same time here in your french neighborhood ;-)

Seems that the current github version is 0.4.0 and latest available in crates.io is 0.3.0 which could explain the issue I'm seeing. Seems that the 0.4.0 was never published, and the difference is the addition of this feature (and switching from chrono to std::time).

I missed the difference in version in this repo when trying to find what I was doing wrong.

**Comment by michaelvanstraten** [comment]
Yeah, so version 0.4 was not published since I wanted to stabilize the crate first while also fixing some of the issue related to the chrono crate. The problem was and is currently that I have a lot of work with university which holds me back from doing much open source work. But I hope that my new rhythm will be adjustable to allow for more time for FOS.

**Comment by michaelvanstraten** [comment]
Version, `0.5` has now been published.

Please reopen this if you have any issues.
