### ISSUE TITLE
allowing specific endpoints to be authorized by JWT

### ISSUE THREAD

**Issue by MrAliSalehi** [michaelvanstraten/actix-jwt-auth-middleware#14]
Hi, Thank you for creating this Library.

Im trying to achieve something like this:

```rust

App::new()
      .service(index)
      .service(web::scope("/api")
          .service(login)
          .service(hello))

      .use_jwt(authority,
               web::scope("/api")
                   .service(index)
                   .service(logout)
                   .service(hello2)
      )
```

I want the `/api/login` to be public and reset of the endpoints in that scope be authorized by jwt, but this is not possible because the first scope of "/api" will accept all of the requests containing "api" and will not go in `use_jwt` branch, so you end up with:

/api/login 200
/api/hello 200

/api/logout 404

right now you can just authorize the whole scope, which is kinda hard to work with.

I think use_jwt should NOT accept a scope, its a middleware and it should act like one, so maybe something like this:

```rust
web::scope("/api")
.service(hello1)
.wrap(use_jwt(..))
.service(hello2)
```
and it should allow `/api/hello1` for everyone and only authorize `/api/hello2`.(or vice versa doesn't matter)

I mean, this is the design that most of the frameworks follow...

**Comment by michaelvanstraten** [comment]
I've might have overlooked something in the design of this but did you try wrapping the `index`, `logout`, `hello2` into an empty scope? This should allow you to have a parent scope, `api` have both authenticated and unauthenticed routes.

**Comment by michaelvanstraten** [comment]
`use_jwt` is just a convenience trait, you can always just wrap the service/scope manually, if the above does not work.

Sorry if I am overseeing something here, I am on my phone since it is already late in Germany.

**Comment by MrAliSalehi** [comment]
>  did you try wrapping the `index`, `logout`, `hello2` into an empty scope?

can you explain more? if I set the second scope to empty it will be `/hello2`, `/` and `/logout`

**Comment by michaelvanstraten** [comment]
> ```rust
> App::new()
>       .service(index)
>       .service(web::scope("/api")
>           .service(login)
>           .service(hello))
> 
>       .use_jwt(authority,
>                web::scope("/api")
>                    .service(index)
>                    .service(logout)
>                    .service(hello2)
>       )
> ```

So here you are creating two scopes with the route `"/api"` which are added to the `App` struct. But you can also call `use_jwt` on a [`scope`](https://docs.rs/actix-jwt-auth-middleware/latest/actix_jwt_auth_middleware/use_jwt/trait.UseJWTOnScope.html).

Can you try this?

```rust
App::new()
      .service(index)
      .service(web::scope("/api")
          .service(login)
          .service(hello)
          .use_jwt(authority,
                   web::scope("")
                       .service(logout)
                       .service(hello2)
          ))
```

Of course, you would have to wrap `"index"` individually here, if it should be authenticated.

**Comment by MrAliSalehi** [comment]
yeah that works, thanks!
so the `scope("")`  basically points to `*` which in this case is the parent scope and anything before use_jwt is unauthorized.

but still I'm not sure if its the best design, maybe, IDK; but what im thinking is 
the middleware itself should not define routes inside it, but the routes should be able to add middlewares around them, I think it makes sense this way, just an opinion :D

**Comment by MrAliSalehi** [comment]
one more thing, I know it should be on another issue but just wanted to mention it, the exonum library is not being maintained, its kinda broken, in some ways, I would recommend replacing it with alternatives ...

**Comment by michaelvanstraten** [comment]
If you take a look at the `Cargo.toml` of this crate you will see that the crate is only a dev dependency, in fact it is completely up to the user which crypto backend they use. I only choose it as an example, but I can update it to a maintained on.

**Comment by MrAliSalehi** [comment]
yes but then the Algorithm trait ties the user hands:)

**Comment by michaelvanstraten** [comment]
Why?

**Comment by michaelvanstraten** [comment]
If your backend does not implement the [`jwt_compact::Algorithm`](https://docs.rs/jwt-compact/latest/jwt_compact/trait.Algorithm.html) trait you can either implement the trait directly in the backend crate or define a proxy structure.

**Comment by MrAliSalehi** [comment]
because implementing it manually is kinda hard, I personally have basic knowledge on Cryptography and have no idea whats doing on in there LMAO.
