### ISSUE TITLE
Authorization Header "Error: invalid base64 decoding"

### ISSUE THREAD

**Issue by matzrm** [michaelvanstraten/actix-jwt-auth-middleware#25]
I think there's a bug using _Authorization_ header, because I get ` Error: "invalid base64 decoding"`. 

This error is caused because the word `Bearer` is checked but then not removed from `token_value `inside the method `get_token_from_authorization_header`:

`               
let token_value = if header_value.strip_prefix("Bearer").is_some() {
      header_value.trim()
}
`

**Comment by michaelvanstraten** [comment]
Hey @matzrm, thank you for opening an issue. 

This has actually been fixed in #23, you will have to update the crate to the latest commit in your `Cargo.toml` since a new version has not been published yet.

Sorry for the inconvenience.
