### ISSUE TITLE
Use utoipa_swagger_ui 

### ISSUE THREAD

**Issue by PierreNeumann** [michaelvanstraten/actix-jwt-auth-middleware#5]
We would like to have swaggerUi page to document the rest API of our server.
We stumble upon the following problem: it seems that for swagger it is not possible to use 2 tokens in cookie (access+refresh).
Do you have any workaround ?
For instance, is-it possible to use the middleware without the refresh token ?

**Comment by michaelvanstraten** [comment]
This should be a no issue. 

The [`Authority`](https://docs.rs/actix-jwt-auth-middleware/latest/actix_jwt_auth_middleware/struct.Authority.html) only ever checks the `refresh token` if:
- the `access token` is not present or expired
- and the [`renew_access_token_automatically`](https://docs.rs/actix-jwt-auth-middleware/latest/actix_jwt_auth_middleware/struct.AuthorityBuilder.html#method.renew_access_token_automatically) is set to true.

I am planing to split the crate into a rest/non rest section, which should simplify the hole rest API process (#6).

**Comment by PierreNeumann** [comment]
I found the problem, it was just that swagger_ui don't support access_token in cookie. 
It show a curl command with the cookie but there is no Cookie in the request sent to the API. 

It works using header token and `.enable_header_tokens(true)`
