### ISSUE TITLE
exonum-crypto is a forced feature on jwt-compact, against this crate's documentation

### ISSUE THREAD

**Issue by softestpoly** [michaelvanstraten/actix-jwt-auth-middleware#8]
https://github.com/michaelvanstraten/actix-jwt-auth-middleware/blob/91d6fd4ff41135370b2a49c1dab38cfbd9945c11/Cargo.toml#L26
`exonum-crypto` is enabled as a feature on `jwt-compact` even though the documentation says to refer to that crate's list of supported algorithms
https://github.com/michaelvanstraten/actix-jwt-auth-middleware/blob/91d6fd4ff41135370b2a49c1dab38cfbd9945c11/src/cookie_signer.rs#L88
I'm somewhat new to rust, so I don't know if there is a way around this on my part, but it seems like a mistake. I'm trying to use `ed25519-dalek` or `ed25519-compact` instead of `exonum-crypto` as I want to use a pure-rust crypto implementation.

**Comment by michaelvanstraten** [comment]
Sorry for the confusion. The `exonum-crypto` feature flag should be dev dependency only, I will fix that tomorrow. 

Non the less the actual underlying implementation which is used is completely generic over the `Algorithm` trait defined in the jwt-compact crate. So it should be no problem to use a different implementation as long as the type implements sed trait. 

If you take a look at the first example you will see that the algorithm type is supplied using the `jwt-compact` crate, if you want to use the `ed25519-dalek` variant you will just have to add the feature flag to your dependency link of `jwt-compact`. Like this: 

```toml
# your Cargo.toml file in your crate
[dependencies]
jwt-compact = { version="0.6", features=["ed25519-dalek"] }
```

Now, for example, `jwt_compact::alg::Ed22519` should use the implementation of the `ed25519-dalek` crate. You can pass the algorithm to the `algorithm()` function on the `Authority` builder.

Sorry if any of this is wrong I am currently on my phone and can't check the code my self, but I will get back to you in the morning.
