### ISSUE TITLE
examples/simple.rs does not work on linux

### ISSUE THREAD

**Issue by cjsmocjsmo** [michaelvanstraten/actix-jwt-auth-middleware#9]
While implementing actix-jwt-auth-middleware I noticed that in [examples/simple.rs](https://github.com/michaelvanstraten/actix-jwt-auth-middleware/blob/master/examples/simple.rsl) the dependency [exonum_crypto](https://crates.io/crates/exonum-crypto) is no longer available for linux (I'm using Ubuntu), is there a drop in replacement for this dependency to generate the needed key pairs?

Thanks for your assistance

**Comment by michaelvanstraten** [comment]
Yes of course the crypto graphic backend is general over the [`Algorithem`](https://docs.rs/jwt-compact/latest/jwt_compact/trait.Algorithm.html) trait, this trait is implemented for many algorithms in different crates.

Please refer to [`this section`](https://docs.rs/jwt-compact/latest/jwt_compact/index.html#supported-algorithms) of the JWT-compact crate, if you find one please open a PR and switch out the crypto graphic backend.

**Comment by cjsmocjsmo** [comment]
After doing a much deeper dive info the docs this fixed my problem:

`
sudo apt-get install -y  build-essential 
    jq 
    libsodium-dev 
    libsnappy-dev 
    libssl-dev 
    pkg-config 
    rocksdb-tools 
    librocksdb-dev 
    librocksdb7.8 
    librust-clang-sys+libloading-dev 
    librust-clang-sys-dev 
    libprotobuf-dev 
    libprotoc-dev 
    protobuf-compiler
`

Ubuntu 23.04 lunar.

Sorry for the noise :)

**Comment by michaelvanstraten** [comment]
No problem, can i mark this as fixed?

**Comment by cjsmocjsmo** [comment]
Might be nice to place this in the README so other linux users won't have to go chase all this down :)

**Comment by cjsmocjsmo** [comment]
Everything builds now so yes please close.

**Comment by michaelvanstraten** [comment]
> Might be nice to place this in the README so other linux users won't have to go chase all this down :)

Would you do that?
